name: Deploy the application to google cloud run
on:
  push:
    
  

jobs:
  demo_ci_cd_build:
    name: cloud run deploy
    runs-on: ubuntu-latest
    steps:

      -name: Checkout
      uses: actions/checkout@master

      -name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      env:
        DEFAULT_BRANCH: main
        service_account_key: ${{secrets.GCP_SA_KEY}}

      -name: Use gcloud CLI
      run: gcloud info

      -name: Configure project id
      run: gcloud config set project us-gcp-ame-con-116-npd-1

      -name: Configure docker to use the gcloud command line as a credential helper
      run: gcloud auth configure-docker -q

      -name: Push image to google container registry
      run: docker push gcr.io/us-gcp-ame-con-116-npd-1/$SERVICE_NAME

      -name: DEPLOY
      run: gcloud run deploy $SERVICE_NAME -image gcr.io/us-gcp-ame-con-116-npd-1/$SERVICE_NAME --max-instances 3 --min-instances 2 --platform managed --region us-west2 --allow-unauthenticated
